#!/usr/bin/bash
uic -g python -o ./UI/ui_main_window.py ./UI/main_window.ui
uic -g python -o ./UI/ui_rebuild_window.py ./UI/rebuild_window.ui
uic -g python -o ./UI/ui_update_quotes_window.py ./UI/quotes_update.ui
uic -g python -o ./UI/ui_account_choice_dlg.py ./UI/account_choice_dlg.ui
uic -g python -o ./UI/ui_active_choice_dlg.py ./UI/active_choice_dlg.ui
uic -g python -o ./UI/ui_peer_choice_dlg.py ./UI/peer_choice_dlg.ui
uic -g python -o ./UI/ui_account_type_dlg.py ./UI/account_type_dlg.ui
uic -g python -o ./UI/ui_category_choice.py ./UI/category_choice_dlg.ui

sed -i 's/QString()/""/g' ./UI/ui_main_window.py
sed -i 's/QUrl, Qt)/QUrl, Qt, QDate)/' ./UI/ui_main_window.py
sed -i 's/import AccountSelector/from CustomUI.account_select import AccountSelector/' ./UI/ui_main_window.py
sed -i 's/import AccountButton/from CustomUI.account_select import AccountButton/' ./UI/ui_main_window.py
sed -i 's/import ActiveSelector/from CustomUI.active_select import ActiveSelector/' ./UI/ui_main_window.py
sed -i 's/import PeerSelector/from CustomUI.peer_select import PeerSelector/' ./UI/ui_main_window.py
