# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QSplitter, QStatusBar, QVBoxLayout,
    QWidget)

from jal.widgets.custom.log_viewer import LogViewer
from jal.widgets.mdi import TabbedMdiArea

class Ui_JAL_MainWindow(object):
    def setupUi(self, JAL_MainWindow):
        if not JAL_MainWindow.objectName():
            JAL_MainWindow.setObjectName(u"JAL_MainWindow")
        JAL_MainWindow.resize(835, 436)
        JAL_MainWindow.setMinimumSize(QSize(0, 0))
        self.actionOperations = QAction(JAL_MainWindow)
        self.actionOperations.setObjectName(u"actionOperations")
        self.actionBackup = QAction(JAL_MainWindow)
        self.actionBackup.setObjectName(u"actionBackup")
        self.actionRestore = QAction(JAL_MainWindow)
        self.actionRestore.setObjectName(u"actionRestore")
        self.action_Re_build_Ledger = QAction(JAL_MainWindow)
        self.action_Re_build_Ledger.setObjectName(u"action_Re_build_Ledger")
        self.actionDeleteAllData = QAction(JAL_MainWindow)
        self.actionDeleteAllData.setObjectName(u"actionDeleteAllData")
        self.actionExit = QAction(JAL_MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionExit.setMenuRole(QAction.MenuRole.QuitRole)
        self.actionAccounts = QAction(JAL_MainWindow)
        self.actionAccounts.setObjectName(u"actionAccounts")
        self.actionAssets = QAction(JAL_MainWindow)
        self.actionAssets.setObjectName(u"actionAssets")
        self.actionPeers = QAction(JAL_MainWindow)
        self.actionPeers.setObjectName(u"actionPeers")
        self.actionCategories = QAction(JAL_MainWindow)
        self.actionCategories.setObjectName(u"actionCategories")
        self.actionTags = QAction(JAL_MainWindow)
        self.actionTags.setObjectName(u"actionTags")
        self.actionBaseCurrency = QAction(JAL_MainWindow)
        self.actionBaseCurrency.setObjectName(u"actionBaseCurrency")
        self.actionQuoteHistory = QAction(JAL_MainWindow)
        self.actionQuoteHistory.setObjectName(u"actionQuoteHistory")
        self.actionTokenBlacklist = QAction(JAL_MainWindow)
        self.actionTokenBlacklist.setObjectName(u"actionTokenBlacklist")
        self.actionImportShopReceipt = QAction(JAL_MainWindow)
        self.actionImportShopReceipt.setObjectName(u"actionImportShopReceipt")
        self.action_LoadQuotes = QAction(JAL_MainWindow)
        self.action_LoadQuotes.setObjectName(u"action_LoadQuotes")
        self.actionLoadTokenLists = QAction(JAL_MainWindow)
        self.actionLoadTokenLists.setObjectName(u"actionLoadTokenLists")
        self.PrepareTaxForms = QAction(JAL_MainWindow)
        self.PrepareTaxForms.setObjectName(u"PrepareTaxForms")
        self.PrepareFlowReport = QAction(JAL_MainWindow)
        self.PrepareFlowReport.setObjectName(u"PrepareFlowReport")
        self.actionMergeRuTaxFiles = QAction(JAL_MainWindow)
        self.actionMergeRuTaxFiles.setObjectName(u"actionMergeRuTaxFiles")
        self.actionPreferences = QAction(JAL_MainWindow)
        self.actionPreferences.setObjectName(u"actionPreferences")
        self.actionPreferences.setMenuRole(QAction.MenuRole.PreferencesRole)
        self.actionDocumentation = QAction(JAL_MainWindow)
        self.actionDocumentation.setObjectName(u"actionDocumentation")
        self.actionFAQ = QAction(JAL_MainWindow)
        self.actionFAQ.setObjectName(u"actionFAQ")
        self.actionErrorMessages = QAction(JAL_MainWindow)
        self.actionErrorMessages.setObjectName(u"actionErrorMessages")
        self.actionReportProblem = QAction(JAL_MainWindow)
        self.actionReportProblem.setObjectName(u"actionReportProblem")
        self.actionAbout = QAction(JAL_MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionAbout.setMenuRole(QAction.MenuRole.AboutRole)
        self.centralwidget = QWidget(JAL_MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMaximumSize(QSize(16777215, 16777215))
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Orientation.Vertical)
        self.mdiArea = TabbedMdiArea(self.splitter)
        self.mdiArea.setObjectName(u"mdiArea")
        self.splitter.addWidget(self.mdiArea)
        self.Logs = LogViewer(self.splitter)
        self.Logs.setObjectName(u"Logs")
        self.splitter.addWidget(self.Logs)

        self.verticalLayout.addWidget(self.splitter)

        JAL_MainWindow.setCentralWidget(self.centralwidget)
        self.MainMenu = QMenuBar(JAL_MainWindow)
        self.MainMenu.setObjectName(u"MainMenu")
        self.MainMenu.setGeometry(QRect(0, 0, 835, 24))
        self.menuLedger = QMenu(self.MainMenu)
        self.menuLedger.setObjectName(u"menuLedger")
        self.menu_Data = QMenu(self.MainMenu)
        self.menu_Data.setObjectName(u"menu_Data")
        self.menuImport = QMenu(self.MainMenu)
        self.menuImport.setObjectName(u"menuImport")
        self.menuStatement = QMenu(self.menuImport)
        self.menuStatement.setObjectName(u"menuStatement")
        self.menuBlockchain = QMenu(self.menuImport)
        self.menuBlockchain.setObjectName(u"menuBlockchain")
        self.menuReports = QMenu(self.MainMenu)
        self.menuReports.setObjectName(u"menuReports")
        self.menuTax = QMenu(self.MainMenu)
        self.menuTax.setObjectName(u"menuTax")
        self.menuSettings = QMenu(self.MainMenu)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuLanguage = QMenu(self.menuSettings)
        self.menuLanguage.setObjectName(u"menuLanguage")
        self.menuHelp = QMenu(self.MainMenu)
        self.menuHelp.setObjectName(u"menuHelp")
        JAL_MainWindow.setMenuBar(self.MainMenu)
        self.StatusBar = QStatusBar(JAL_MainWindow)
        self.StatusBar.setObjectName(u"StatusBar")
        JAL_MainWindow.setStatusBar(self.StatusBar)

        self.MainMenu.addAction(self.menuLedger.menuAction())
        self.MainMenu.addAction(self.menu_Data.menuAction())
        self.MainMenu.addAction(self.menuImport.menuAction())
        self.MainMenu.addAction(self.menuReports.menuAction())
        self.MainMenu.addAction(self.menuTax.menuAction())
        self.MainMenu.addAction(self.menuSettings.menuAction())
        self.MainMenu.addAction(self.menuHelp.menuAction())
        self.menuLedger.addAction(self.actionOperations)
        self.menuLedger.addSeparator()
        self.menuLedger.addAction(self.actionBackup)
        self.menuLedger.addAction(self.actionRestore)
        self.menuLedger.addAction(self.action_Re_build_Ledger)
        self.menuLedger.addSeparator()
        self.menuLedger.addAction(self.actionDeleteAllData)
        self.menuLedger.addSeparator()
        self.menuLedger.addAction(self.actionExit)
        self.menu_Data.addAction(self.actionAccounts)
        self.menu_Data.addAction(self.actionAssets)
        self.menu_Data.addAction(self.actionPeers)
        self.menu_Data.addAction(self.actionCategories)
        self.menu_Data.addAction(self.actionTags)
        self.menu_Data.addSeparator()
        self.menu_Data.addAction(self.actionBaseCurrency)
        self.menu_Data.addAction(self.actionQuoteHistory)
        self.menu_Data.addAction(self.actionTokenBlacklist)
        self.menuImport.addAction(self.menuStatement.menuAction())
        self.menuImport.addAction(self.menuBlockchain.menuAction())
        self.menuImport.addAction(self.actionImportShopReceipt)
        self.menuImport.addSeparator()
        self.menuImport.addAction(self.action_LoadQuotes)
        self.menuImport.addAction(self.actionLoadTokenLists)
        self.menuTax.addAction(self.PrepareTaxForms)
        self.menuTax.addAction(self.PrepareFlowReport)
        self.menuTax.addSeparator()
        self.menuTax.addAction(self.actionMergeRuTaxFiles)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuSettings.addAction(self.menuLanguage.menuAction())
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionFAQ)
        self.menuHelp.addAction(self.actionErrorMessages)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionReportProblem)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)

        self.retranslateUi(JAL_MainWindow)

        QMetaObject.connectSlotsByName(JAL_MainWindow)
    # setupUi

    def retranslateUi(self, JAL_MainWindow):
        JAL_MainWindow.setWindowTitle(QCoreApplication.translate("JAL_MainWindow", u"jal", None))
        self.actionOperations.setText(QCoreApplication.translate("JAL_MainWindow", u"&Operations", None))
        self.actionBackup.setText(QCoreApplication.translate("JAL_MainWindow", u"&Backup...", None))
        self.actionRestore.setText(QCoreApplication.translate("JAL_MainWindow", u"&Restore...", None))
        self.action_Re_build_Ledger.setText(QCoreApplication.translate("JAL_MainWindow", u"Re-build &ledger...", None))
        self.actionDeleteAllData.setText(QCoreApplication.translate("JAL_MainWindow", u"&Delete all data...", None))
        self.actionExit.setText(QCoreApplication.translate("JAL_MainWindow", u"&Exit", None))
        self.actionAccounts.setText(QCoreApplication.translate("JAL_MainWindow", u"&Accounts", None))
        self.actionAssets.setText(QCoreApplication.translate("JAL_MainWindow", u"A&ssets", None))
        self.actionPeers.setText(QCoreApplication.translate("JAL_MainWindow", u"&Peers", None))
        self.actionCategories.setText(QCoreApplication.translate("JAL_MainWindow", u"&Categories", None))
        self.actionTags.setText(QCoreApplication.translate("JAL_MainWindow", u"&Tags", None))
        self.actionBaseCurrency.setText(QCoreApplication.translate("JAL_MainWindow", u"&Base currency", None))
        self.actionQuoteHistory.setText(QCoreApplication.translate("JAL_MainWindow", u"Quote &history", None))
        self.actionTokenBlacklist.setText(QCoreApplication.translate("JAL_MainWindow", u"To&ken blacklist", None))
        self.actionImportShopReceipt.setText(QCoreApplication.translate("JAL_MainWindow", u"&Receipt...", None))
        self.action_LoadQuotes.setText(QCoreApplication.translate("JAL_MainWindow", u"&Download quotes...", None))
        self.actionLoadTokenLists.setText(QCoreApplication.translate("JAL_MainWindow", u"Download token &lists", None))
        self.PrepareTaxForms.setText(QCoreApplication.translate("JAL_MainWindow", u"Investment &tax report", None))
        self.PrepareFlowReport.setText(QCoreApplication.translate("JAL_MainWindow", u"Foreign accounts &flow report", None))
        self.actionMergeRuTaxFiles.setText(QCoreApplication.translate("JAL_MainWindow", u"&Merge Russian tax files (*.de5)...", None))
        self.actionPreferences.setText(QCoreApplication.translate("JAL_MainWindow", u"&Preferences", None))
        self.actionDocumentation.setText(QCoreApplication.translate("JAL_MainWindow", u"&Documentation", None))
        self.actionFAQ.setText(QCoreApplication.translate("JAL_MainWindow", u"&FAQ", None))
        self.actionErrorMessages.setText(QCoreApplication.translate("JAL_MainWindow", u"Description of &error messages", None))
        self.actionReportProblem.setText(QCoreApplication.translate("JAL_MainWindow", u"&Report a problem", None))
        self.actionAbout.setText(QCoreApplication.translate("JAL_MainWindow", u"&About JAL", None))
        self.menuLedger.setTitle(QCoreApplication.translate("JAL_MainWindow", u"&Ledger", None))
        self.menu_Data.setTitle(QCoreApplication.translate("JAL_MainWindow", u"&Data", None))
        self.menuImport.setTitle(QCoreApplication.translate("JAL_MainWindow", u"&Import", None))
        self.menuStatement.setTitle(QCoreApplication.translate("JAL_MainWindow", u"&Statement", None))
        self.menuBlockchain.setTitle(QCoreApplication.translate("JAL_MainWindow", u"&Blockchain", None))
        self.menuReports.setTitle(QCoreApplication.translate("JAL_MainWindow", u"&Reports", None))
        self.menuTax.setTitle(QCoreApplication.translate("JAL_MainWindow", u"&Tax", None))
        self.menuSettings.setTitle(QCoreApplication.translate("JAL_MainWindow", u"&Settings", None))
        self.menuLanguage.setTitle(QCoreApplication.translate("JAL_MainWindow", u"L&anguage", None))
        self.menuHelp.setTitle(QCoreApplication.translate("JAL_MainWindow", u"&Help", None))
    # retranslateUi

