#!/usr/bin/bash
/usr/lib/qt6/uic -g python -o ./ui/ui_main_window.py ./ui/main_window.ui
/usr/lib/qt6/uic -g python -o ./ui/ui_operations_widget.py ./ui/operations_widget.ui
/usr/lib/qt6/uic -g python -o ./ui/ui_reports_widget.py ./ui/reports_widget.ui
/usr/lib/qt6/uic -g python -o ./ui/ui_rebuild_window.py ./ui/rebuild_window.ui
/usr/lib/qt6/uic -g python -o ./ui/ui_update_quotes_window.py ./ui/quotes_update.ui
/usr/lib/qt6/uic -g python -o ./ui/ui_reference_data_dlg.py ./ui/reference_data_dlg.ui
/usr/lib/qt6/uic -g python -o ./ui/ui_tax_export_dlg.py ./ui/tax_export_dlg.ui
/usr/lib/qt6/uic -g python -o ./ui/ui_add_asset_dlg.py ./ui/add_asset_dlg.ui
/usr/lib/qt6/uic -g python -o ./ui/ui_select_account_dlg.py ./ui/select_account_dlg.ui
/usr/lib/qt6/uic -g python -o ./ui/ui_slip_import_dlg.py ./ui/slip_import_dlg.ui
/usr/lib/qt6/uic -g python -o ./ui/ui_login_fns_dlg.py ./ui/login_fns_dlg.ui
/usr/lib/qt6/uic -g python -o ./ui/reports/ui_holdings_report.py ./ui/reports/holdings_report.ui
/usr/lib/qt6/uic -g python -o ./ui/reports/ui_tax_estimation.py ./ui/reports/tax_estimation.ui
/usr/lib/qt6/uic -g python -o ./ui/reports/ui_income_spending_report.py ./ui/reports/income_spending_report.ui

/usr/lib/qt6/bin/lupdate -no-obsolete jal.pro


